# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: NjZiMzViZTFlZTZmNGNjOTFiMTk4NWU3MWZjZTQ5YTc1MWFkOGE4NjI1ZjEwMzgxZWZjZGViMGMxMDA4NGY3ZTgwZDk4Njg0OWQ3YmI4MmYyMTNmZWM1MTllODZmNjBmZGY0MmI3MGQ4NDFhNTk4YmI5OGM1ODQ1MzlhOTEyMzU=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
